### ISSUE TITLE
the owner of this repository is chort

### ISSUE THREAD

**Issue by D1scoDancer** [DZA-Mirai/proweb#2]

**Comment by DZA-Mirai** [comment]
Vtoroy raz repeat tebe ya chort mne ne nujna team

**Comment by D1scoDancer** [comment]
you need mee

**Comment by D1scoDancer** [comment]
I want to come inside your repository

**Comment by DZA-Mirai** [comment]
Please don't cum inside

**Comment by DZA-Mirai** [comment]
I'm not like this

**Comment by D1scoDancer** [comment]
but you are said to be js developer

**Comment by D1scoDancer** [comment]
they like when some1 is working in their repo

**Comment by DZA-Mirai** [comment]
I don't have js in my repo yet

**Comment by DZA-Mirai** [comment]
You want to cum too early

**Comment by DZA-Mirai** [comment]
You can't do it before me

**Comment by D1scoDancer** [comment]
when i cum there will be a lot of java script

**Comment by DZA-Mirai** [comment]
are you sure a js developer?

**Comment by D1scoDancer** [comment]
my little friend is js developer

**Comment by DZA-Mirai** [comment]
Then I would like to see him in my repo

**Comment by DZA-Mirai** [comment]
He can cum when he want

**Comment by DZA-Mirai** [comment]
come*

**Comment by D1scoDancer** [comment]
He wants to come on your face, but you dont have an avatar

**Comment by DZA-Mirai** [comment]
I'm ready

**Comment by D1scoDancer** [comment]
iam coming

**Comment by DZA-Mirai** [comment]
It was sticky

**Comment by D1scoDancer** [comment]
taste it
